---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

images:
  base_image:
    name: "python:3.10.12"

dependencies:
  ansible_core:
      package_pip: ansible-core==2.15.9
  ansible_runner:
      package_pip: ansible-runner==2.3.4
  python_interpreter:
    python_path: /usr/local/bin/python3
  python: requirements.txt
  galaxy: requirements.yml

additional_build_files:
    - src: files
      dest: files

additional_build_steps:
  prepend_base:
    - RUN apt-get update && apt-get install sshpass -y
    - ADD _build/files/dnf /usr/bin/dnf
  append_final:
    - ADD _build/files/plugins /usr/share/ansible/plugins/
    - ADD _build/files/roles /usr/share/ansible/roles/
    - ADD _build/files/deprecated.conf /etc/ssh/ssh_config.d/
    - ADD _build/files/ansible.cfg /etc/ansible/ansible.cfg